In [1]:
import numpy as np
import tensorflow as tf

In [2]:
[1, 2, 3]

[1, 2, 3]

In [3]:
[[1, 2, 3]]

[[1, 2, 3]]

In [4]:
arr = np.array([1, 2, 3])

In [5]:
arr

array([1, 2, 3])

In [6]:
arr.shape

(3,)

In [ ]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.shape

## Create Tensor
    * list to tensor
    * tuple to tensor
    * numpy array to tensor

In [8]:
# Create Tensor : list to tensor
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [9]:
# Create Tensor : tuple to tensor
tf.constant(((1, 2, 3), (4, 5, 6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [10]:
# Create Tensor : numpy array to tensor
arr = np.array([[1, 2, 3], [4, 5, 6]])
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

## Data type & type cast
    * numpy array : np.astype()
    * tensor : tf.cast

In [11]:
# shape
tensor.shape

TensorShape([2, 3])

In [12]:
# data type
tensor.dtype

tf.int64

In [13]:
# define data type
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [14]:
# data type conversion for numpy array
arr = np.array([1, 2, 3], dtype=np.float32)
arr

array([1., 2., 3.], dtype=float32)

In [15]:
# use astype for type conversion in np array : np.astype()
arr.astype(np.uint32)

array([1, 2, 3], dtype=uint32)

In [18]:
# use cast for type conversion in tensor : tf.cast()
tensor = tf.cast(tensor, dtype=tf.uint8)
tensor

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

## Tensor to Numpy array
    * {tensor}.numpy()

In [22]:
# tensor to numpy : numpy()
tensor.numpy()

array([1., 2., 3.], dtype=float32)

## Create Random Number

### Normal Distribution

In [20]:
np.random.randn(10)

array([-1.28794553,  0.36053215,  0.21293955,  0.36949386, -0.40103607,
        0.05223692, -0.0038633 , -0.38591143,  0.85796041,  0.33250861])

In [21]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.3215911 ,  1.4107507 ,  0.00687301],
       [-0.65350324,  0.48088774,  0.0809207 ],
       [ 1.6908302 ,  2.1607099 ,  0.5987719 ]], dtype=float32)>

### Uniform Distribution

In [23]:
tf.random.uniform([5, 5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.5433177 , 0.01075697, 0.34880817, 0.90933764, 0.3019191 ],
       [0.59021235, 0.16172028, 0.18461323, 0.4403851 , 0.08266854],
       [0.56784785, 0.4345752 , 0.43370426, 0.4257313 , 0.1223141 ],
       [0.8886987 , 0.49177277, 0.23118496, 0.18910778, 0.9629569 ],
       [0.91180754, 0.22176683, 0.6563754 , 0.15810382, 0.5824046 ]],
      dtype=float32)>